config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'festivelnet#index'
  post '/festivelnet_options' => 'festivelnet#index1'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/festivelnet.rb
class Festivelnet < ApplicationRecord
    def self.list(params)
        arel = Festivelnet.all
        if params[:select1] == 'AND' 
            arel = arel.where("eventname LIKE ?", ("%" + params[:search] + "%")) if params[:search].present?
            arel = arel.where("attendance = ?", params[:attendee]) if params[:attendee].present?	
        else
            arel = arel.where("eventname LIKE ? OR attendance = ?", ("%" + params[:search] + "%"), params[:attendee]) if params[:search].present? && params[:attendee].present?
            arel = arel.where("eventname LIKE ?", ("%" + params[:search] + "%")) if params[:search].present? && !params[:attendee].present?
            arel = arel.where("attendance = ?",  params[:attendee]) if !params[:search].present? && params[:attendee].present?
        end
        if params[:select2] == 'AND' 
            arel = arel.where("date BETWEEN ? AND ?", params[:from_date][0], params[:to_date][0]) if params[:from_date][0].present? && params[:to_date][0].present?
            arel = arel.where("date >= ?", params[:from_date]) if params[:from_date].present? && !params[:to_date].present?
            arel = arel.where("date <= ?", params[:to_date]) if params[:to_date].present? && !params[:from_date].present?
        else
            result = Array.new
            result = Festivelnet.where("date BETWEEN ? AND ?", params[:from_date][0], params[:to_date][0]) if params[:from_date][0].present? && params[:to_date][0].present?
            result = Festivelnet.where("date >= ?", params[:from_date]) if params[:from_date].present? && !params[:to_date].present?
            result = Festivelnet.where("date <= ?", params[:to_date]) if params[:to_date].present? && !params[:from_date].present?
            arel = (arel + result)
        end
        arel	
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/festivelnet_controller.rb
class FestivelnetController < ApplicationController
    def index1
        @title = "Lists of event"
        @festivelnets = Festivelnet.list(params)
        @data = Array.new
        @festivelnets.each do |x|
            @data << {name: x.eventname, attendance: x.attendance, start_date: x.date, show_director: x.show_director, show_director_email_id: x.show_director_email_id}
         end
    end
    
    def index
        @response = Festivelnet.all
        @data1 = Array.new
        @response.each do |x|
            @data1 << {name: x.eventname, attendance: x.attendance, start_date: x.date, show_director: x.show_director, show_director_email_id: x.show_director_email_id}
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/festivelnet_helper.rb
module FestivelnetHelper
end

app/views/festivelnet/index.html.erb
<h1> Lists </h1>
<%= form_tag festivelnet_options_path, :class=>"container" do%>
        EVENT NAME <%= text_field_tag :search, params[:search], :id => 'search_name',:class=>"input_field" %>
        <%= select_tag :select1, options_for_select([['OR', 'OR'], ['AND', 'AND']]),:class=>"input_field" %> 
        ATTENDEES <%= text_field_tag :attendee, params[:attendee], :id => 'search_attend',:class=>"input_field" %>
        <%= select_tag :select2, options_for_select([['OR', 'OR'], ['AND', 'AND']]),:class=>"input_field" %> 
        START DATE   <%= date_field :from_date, params[:from_date], :id => 'search_date',:class=>"input_field" %>
        END DATE <%= date_field :to_date, params[:to_date], :id => 'search_field1',:class=>"input_field" %><br><br>
         <%= submit_tag "FILTER", method: "post" ,:class=>"button"%> 
 <% end %><br>

 <table border = 1 id="table">
  <tr>
    <th>EventName</th>
    <th>Attendees</th>
    <th>Start Date</th>
    <th>Show Director</th>
    <th>Contact Email</th>
  </tr>
  <% @data1.each do |x| %>
        <tr>
                <td> <%= x[:name] %> </td>
                <td> <%= x[:attendance] %> </td>
                <td> <%= x[:start_date] %> </td>
                <td> <%= x[:show_director] %> </td>
                <td> <%= x[:show_director_email_id] %> </td>
         </tr>
       <% end %>

</table>

<style type="text/css">  
#table{
border-collapse: collapse;
width: 100%;
font-family: Helvetica Neue;
}
th,td{
        border: 1px solid #ddd;
        padding: 7px;
        font-size: 14px;
}
#table tr:nth-child(even){
        background-color: #f2f2f2;
}

#table tr:hover {
        background-color: #ddd;
}

.input_field{
        font-family: Helvetica Neue;
        border-radius: 4px;
}

h1{
        text-align: center;
        font-family: Optima;
}

.container{
        display: flex;
        justify-content: space-around;
        font-family: Optima;
        padding: 30px;
        align-content: center;
}

.button{
        padding: 5px 10px 5px 10px;
        border-radius: 5px;
        font-size: 10px;
        font-family: Helvetica Neue;
        background-color: #ddd;
        color: #000;
        border: none;
}
</style> 

app/views/festivelnet/index1.html.erb
<h1><%= @title %></h1>
<table border = 1 id="table">
<tr>
      <th>EventName</th>
  <th>Attendees</th>
  <th>Start Date</th>
  <th>Show Director</th>
  <th>Contact Email</th>
</tr>
  <% @data.each do |x| %>
  <tr>
      <td> <%= x[:name] %> </td>
      <td> <%= x[:attendance] %> </td>
      <td> <%= x[:start_date] %> </td>
      <td> <%= x[:show_director] %> </td>
      <td> <%= x[:show_director_email_id] %> </td>
  </tr>
  <% end %>
</table>
     <style type="text/css">  
     #table{
     border-collapse: collapse;
     width: 100%;
     font-family: Helvetica Neue;
     }
     th,td{
             border: 1px solid #ddd;
             padding: 8px;
     }
     #table tr:nth-child(even){
             background-color: #f2f2f2;
     }
     
     #table tr:hover {
             background-color: #ddd;
     }
     </style> 
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodFilter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>